[versions]
activityCompose = "1.12.2"
agp = "9.0.0"
jacksonCore = "2.20.1"
jacksonAnnotations = "2.20"
jacksonDatabind = "2.20.1"
jacksonModuleKotlin = "2.20.1"
javaAndroidWebsocketClient = "2.0.2"
appcompat = "1.7.1"
fastscroll = "1.3.0"
lifecycleLivedataKtx = "2.10.0"
material = "1.14.0-alpha01"
activity = "1.12.2"
constraintlayout = "2.2.1"
glide = "5.0.5"
material3 = "1.4.0"
media = "1.7.1"
media3Exoplayer = "1.9.0"
recyclerview = "1.4.0"
kotlin = "2.3.0"
coreKtx = "1.17.0"
swiperefreshlayout = "1.2.0"
uiToolingPreview = "1.10.1"
cardview = "1.0.0"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
jackson-core = { module = "com.fasterxml.jackson.core:jackson-core", version.ref = "jacksonCore" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jacksonAnnotations" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jacksonDatabind" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jacksonModuleKotlin" }
java-android-websocket-client = { module = "dev.gustavoavila:java-android-websocket-client", version.ref = "javaAndroidWebsocketClient" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
fastscroll = { module = "me.zhanghai.android.fastscroll:library", version.ref = "fastscroll" }
lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
media = { module = "androidx.media:media", version.ref = "media" }
media3-common = { module = "androidx.media3:media3-common", version.ref = "media3Exoplayer" }
media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Exoplayer" }
media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Exoplayer" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swiperefreshlayout" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "uiToolingPreview" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "uiToolingPreview" }
cardview = { group = "androidx.cardview", name = "cardview", version.ref = "cardview" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
